### ISSUE TITLE
How to make revisions to vars defined in .env

### ISSUE THREAD

**Issue by pbchase** [123andy/redcap-docker-compose#7]
To use this tool I need to make at least _one_ modification to the .env file.  As this is a committed file, it puts me at risk of committing a `.env` during my development work that would break someone else's environment. I need a good way to handle this, but I don't see a great framework for that. The best I have found thus far is to declare a second .env file in the docker-compose.yml e.g., an `override.env` could be referenced like this:

```
  db:
    image: mysql:5.7
#    container_name: redcap-db
    env_file: 
      - .env
      - override.env
    restart: always
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
      - ${LOGS_DIR}:/var/log/mysql
      - ${MYSQL_OVERRIDES}:/etc/mysql/mysql.conf.d
    ports:
     - "${MYSQL_PORT}:3306"
```

If `override.env` were added to .gitignore it could be permanently excluded from the repo. I could add the few ENV var overrides I need in override.env. 

The downside of this is that the file must exist of composer will fail. At the very least an empty file by that name must exist. It's a trivial thing for a developer, but yet another hurdle for a non-technical user. 

If we are trying to make file friendly to non-technical users, we might also want to name it something like `override-env.txt` to reduce barriers for GUI users.
